// Parse the QR payload printed on a SENACSA guía (generated by SIGOR III).
//
// Example input:
//   29/01/2026. Cota:15101267000203. Guia:91097042. PO:157768.
//   EO:1526010016. CO:23° 50' 44.29779'' S  58° 52' 32.99377'' O
//   OPD:80050418. ED:0103780002. CD:23° 19' 57.99728'' S  56° 42' 35.9967'' O
//   OF:Engorde. A:Nov 34. DM 16.

import { parseDMSPair } from './coordinates.js';
import { canonicalizeCategoria } from './categorias.js';

function pick(rx, src) {
  const m = src.match(rx);
  return m ? m[1].trim() : null;
}

function parseFechaDMY(raw) {
  if (!raw) return null;
  const m = raw.match(/^(\d{2})\/(\d{2})\/(\d{4})/);
  if (!m) return null;
  return `${m[3]}-${m[2]}-${m[1]}`;
}

function parseComposicion(segment) {
  // "Nov 34. DM 16." -> { NOV: 34, DMA: 16 }
  if (!segment) return { composicion: {}, cantidad_total: 0 };
  const composicion = {};
  let total = 0;
  const re = /([A-Za-zÑñ]+)\s+(\d+)/g;
  let m;
  while ((m = re.exec(segment)) !== null) {
    const key = canonicalizeCategoria(m[1]);
    const qty = Number(m[2]);
    if (!key || !Number.isFinite(qty)) continue;
    composicion[key] = (composicion[key] ?? 0) + qty;
    total += qty;
  }
  return { composicion, cantidad_total: total };
}

export function parseGuiaQR(raw) {
  if (!raw) throw new Error('Payload de QR vacío');
  const src = String(raw).replace(/\s+/g, ' ').trim();

  const guia_nro = pick(/\bGuia:\s*([^.\s]+)/, src);
  if (!guia_nro) throw new Error('No se encontró número de guía en el QR');

  const fecha_emision = parseFechaDMY(src);
  const cota = pick(/\bCota:\s*([^.\s]+)/, src);
  const po = pick(/\bPO:\s*([^.\s]+)/, src);
  const eo = pick(/\bEO:\s*([^.\s]+)/, src);
  const opd = pick(/\bOPD:\s*([^.\s]+)/, src);
  const ed = pick(/\bED:\s*([^.\s]+)/, src);
  const finalidad = pick(/\bOF:\s*([^.]+?)\./, src);
  const animales_raw = pick(/(?:^|[.\s])A:\s*([^]+)$/, src);

  const coRaw = pick(/\bCO:\s*([^]+?)\s+OPD:/, src);
  const cdRaw = pick(/\bCD:\s*([^]+?)\s+OF:/, src);
  const co = coRaw ? parseDMSPair(coRaw) : null;
  const cd = cdRaw ? parseDMSPair(cdRaw) : null;

  const { composicion, cantidad_total } = parseComposicion(animales_raw);

  return {
    raw,
    guia_nro,
    fecha_emision,
    cota,
    origen: {
      proprietario_codigo: po,
      establecimiento_codigo: eo,
      coordenadas: co,
      coordenadas_dms: coRaw ? coRaw.trim() : null,
    },
    destino: {
      proprietario_codigo: opd,
      establecimiento_codigo: ed,
      coordenadas: cd,
      coordenadas_dms: cdRaw ? cdRaw.trim() : null,
    },
    finalidad: finalidad || null,
    composicion,
    cantidad_total,
  };
}
